---
vagrant:
  boxes:
    - name: test-sanity-check-node-1
  global:
    memory: 512
    cpus: 1
    boot_timeout: 300
    nvme_disks:
      data:
        size: 1024
      data2:
        size: 1024
    virtualbox_cfg:
      enabled: "true" # If not "true" then omit from Vagrantfile
      box: "generic/ubuntu1804"
      enable_sse4: "true"
      nvme_disk_postfix: 'vdi'
      nvme_disk_path: '.vagrant/nvme_disks/'
      nvme_disk_prefix: 'nvme_disk'
      append_project_name_to_nvme_disk_path: 'true'
    libvirt_cfg:
      enabled: "true" # If not "true" then omit from Vagrantfile
      box: "generic/ubuntu1804"
      machine_type: 'q35'
      nvme_disk_postfix: 'qcow2'
      nvme_disk_id_prefix: 'drv'
      qemu_group: 'qemu'
      emulator_path: '/usr/bin/qemu-system-x86_64'
      nvme_disk_path: '$HOME/.local/share/libvirt/images/'
      append_project_name_to_nvme_disk_path: 'true'

ansible:
  roles:
    - src: https://github.com/pwyoung/ansible-role-sanity-check
      name: ansible-role-sanity-check
      scm: git
      version: 0.0.2
  playbooks:
    - name: "ansible-playbook-sanity-check"
      scm: git
      entry: playbook.yaml # Defaults to site.yml
      src: "https://github.com/pwyoung/ansible-playbook-sanity-check"
      version: master
  inventory:
    all:
      vars:
        ansible_python_interpreter: "/usr/bin/python3"
      hosts:
        test-sanity-check-node-1:
      children:
        group-a:
          hosts:
            test-sanity-check-node-1:
  extra_vars:
    test_msg: "SANITY CHECK TEST MESSAGE"
    
